### ISSUE TITLE
Why do not you call the 'AppRegistry.registerComponent' function? 

### ISSUE THREAD

**Issue by yahue** [jasonhealy/react-native-typescript-starter#4]
Help！
 Do not go wrong when the project is running?
I copy your code, run in my project, can not compile through.
![simulator screen shot 2017 8 27 11 40 50](https://user-images.githubusercontent.com/8090320/29746937-a03e770a-8b1c-11e7-8f62-dca7c7185d05.png)

**Comment by jasonhealy** [comment]
This starter repo is due an update which will happen soon. AppRegistry is abstracted by react-native-navigation library. Ensure you run tsc command in separate terminal tab to build typescript.
